// src/data/extended/realEstate.ts
import type { CalculatorEntry } from '../calculatorRegistry';

export const realEstateCalculators: CalculatorEntry[] = [
  {
    id: 'rental-yield-calculator',
    category: 'real-estate',
    name: 'Rental Yield Calculator',
    title: 'Free Rental Yield Calculator — Gross & Net Property Returns',
    description: 'Calculate gross and net rental yield percentages on real estate investments with recurring expense deductions.',
    badge: 'High-Demand',
    badgeColor: 'text-cyan border-cyan/30 bg-cyan/10',
    formula: {
      name: 'Gross & Net Rental Yield Formulas',
      expression: 'Gross Yield = (Annual Rent ÷ Purchase Price) × 100 ; Net Yield = [(Annual Rent - Expenses) ÷ Purchase Price] × 100',
      explanation: 'Gross rental yield evaluates baseline rental income relative to asset purchase cost. Net rental yield factors in recurring property taxes, HOA maintenance, and insurance.',
      variables: [
        { symbol: 'Annual Rent', meaning: 'Total annual rental revenue (Monthly Rent × 12)' },
        { symbol: 'Purchase Price', meaning: 'Total acquisition cost of property including closing fees' },
        { symbol: 'Expenses', meaning: 'Annual property taxes, insurance, HOA, and maintenance' },
      ],
    },
    example: {
      title: 'Worked Example: $350,000 Single Family Rental',
      scenario: 'You purchase an investment property for $350,000, achieving $2,400 monthly rent ($28,800/yr) with $4,800 in annual taxes, insurance, and maintenance.',
      steps: [
        {
          number: 1,
          title: 'Calculate Gross Annual Yield',
          description: 'Gross Yield = ($28,800 ÷ $350,000) × 100 = 8.23%.',
          mathExpression: '8.23%',
        },
        {
          number: 2,
          title: 'Calculate Net Annual Yield',
          description: 'Net Yield = [($28,800 - $4,800) ÷ $350,000] × 100 = 6.86%.',
          mathExpression: '6.86%',
        },
      ],
      conclusion: 'The property delivers a gross return of 8.23% and a net operating return of 6.86% before debt service.',
    },
    faqs: [
      {
        question: 'What is considered a good rental yield?',
        answer: 'In most developed property markets, a gross rental yield between 5% and 8% is considered healthy, while net yields above 5% indicate strong cash-flow efficiency.',
      },
      {
        question: 'What is the difference between rental yield and cap rate?',
        answer: 'Rental yield evaluates return against total asset purchase price, whereas capitalization rate evaluates net operating income against current market value without financing costs.',
      },
    ],
    inputs: [
      { id: 'purchase_price', label: 'Property Purchase Price', type: 'number', defaultValue: 350000, min: 1000, max: 100000000, unit: '$', helpText: 'Total purchase price or acquisition cost' },
      { id: 'monthly_rent', label: 'Monthly Rental Income', type: 'number', defaultValue: 2400, min: 0, max: 1000000, unit: '$', helpText: 'Expected monthly rent collected from tenant' },
      { id: 'annual_expenses', label: 'Annual Operating Expenses', type: 'number', defaultValue: 4800, min: 0, max: 1000000, unit: '$', helpText: 'Annual property tax, insurance, maintenance & HOA' },
    ],
    defaultResult: {
      label: 'Gross Rental Yield',
      initialValue: 8.23,
      decimals: 2,
      secondaryText: 'Net Yield: 6.86% | Annual Cash Flow: $24,000',
      suffix: '%',
      accent: 'cyan',
    },
    computeScript: `
      const price = Math.max(1, Number(inputs.purchase_price) || 350000);
      const rent = Math.max(0, Number(inputs.monthly_rent) || 2400);
      const expenses = Math.max(0, Number(inputs.annual_expenses) || 4800);
      const annualRent = rent * 12;
      const netIncome = Math.max(0, annualRent - expenses);
      const grossYield = (annualRent / price) * 100;
      const netYield = (netIncome / price) * 100;
      return {
        value: grossYield,
        secondaryText: 'Net Yield: ' + netYield.toFixed(2) + '% | Net Annual Income: $' + Math.round(netIncome).toLocaleString(),
        badge: netYield >= 5 ? 'High Cashflow' : 'Standard Yield'
      };
    `,
  },
  {
    id: 'cap-rate-calculator',
    category: 'real-estate',
    name: 'Cap Rate Calculator',
    title: 'Free Cap Rate Calculator — Capitalization Rate & Commercial NOI',
    description: 'Evaluate commercial and residential real estate investment profitability using Net Operating Income (NOI) and asset market valuation.',
    badge: 'Standardized',
    badgeColor: 'text-link border-link/30 bg-link/10',
    formula: {
      name: 'Capitalization Rate Equation',
      expression: 'Cap Rate = (Net Operating Income ÷ Current Market Value) × 100',
      explanation: 'Measures the unleveraged rate of return generated by an income-producing property, excluding mortgage financing debt service.',
      variables: [
        { symbol: 'Net Operating Income (NOI)', meaning: 'Total revenue minus all operating expenses' },
        { symbol: 'Current Market Value', meaning: 'Current sales price or independent appraisal value' },
      ],
    },
    example: {
      title: 'Worked Example: $600,000 Multi-Family Building',
      scenario: 'A duplex generates $52,000 gross annual revenue with $16,000 operating expenses, valued at $600,000.',
      steps: [
        {
          number: 1,
          title: 'Calculate NOI',
          description: 'NOI = $52,000 - $16,000 = $36,000.',
          mathExpression: '$36,000',
        },
        {
          number: 2,
          title: 'Calculate Capitalization Rate',
          description: 'Cap Rate = ($36,000 ÷ $600,000) × 100 = 6.00%.',
          mathExpression: '6.00%',
        },
      ],
      conclusion: 'The duplex yields an unleveraged capitalization rate of 6.00%.',
    },
    faqs: [
      {
        question: 'Does cap rate include mortgage payments?',
        answer: 'No. Cap rate reflects unleveraged operational profitability so investors can objectively compare properties regardless of whether they pay cash or finance.',
      },
      {
        question: 'What is an optimal cap rate range?',
        answer: 'Cap rates typically range between 4% and 10%, depending on property asset class, geographic market liquidity, and tenant lease quality.',
      },
    ],
    inputs: [
      { id: 'property_value', label: 'Property Market Value', type: 'number', defaultValue: 600000, min: 1000, max: 100000000, unit: '$' },
      { id: 'gross_revenue', label: 'Gross Annual Rental Revenue', type: 'number', defaultValue: 52000, min: 0, max: 10000000, unit: '$' },
      { id: 'operating_expenses', label: 'Annual Operating Expenses', type: 'number', defaultValue: 16000, min: 0, max: 10000000, unit: '$' },
    ],
    defaultResult: {
      label: 'Capitalization Rate',
      initialValue: 6.00,
      decimals: 2,
      secondaryText: 'Net Operating Income (NOI): $36,000/yr',
      suffix: '%',
      accent: 'link',
    },
    computeScript: `
      const value = Math.max(1, Number(inputs.property_value) || 600000);
      const revenue = Math.max(0, Number(inputs.gross_revenue) || 52000);
      const expenses = Math.max(0, Number(inputs.operating_expenses) || 16000);
      const noi = Math.max(0, revenue - expenses);
      const capRate = (noi / value) * 100;
      return {
        value: capRate,
        secondaryText: 'Net Operating Income (NOI): $' + Math.round(noi).toLocaleString() + '/yr',
        badge: capRate >= 6 ? 'Prime Return' : 'Growth Asset'
      };
    `,
  },
  {
    id: 'property-tax-calculator',
    category: 'real-estate',
    name: 'Property Tax Calculator',
    title: 'Free Property Tax Calculator — Annual & Monthly Escrow Estimator',
    description: 'Estimate annual, semi-annual, and monthly property tax payments based on local county millage rates and assessed market values.',
    badge: 'County-Aware',
    badgeColor: 'text-violet border-violet/30 bg-violet/10',
    formula: {
      name: 'Property Tax Assessment Formula',
      expression: 'Annual Tax = Assessed Value × (Tax Rate ÷ 100) ; Monthly Escrow = Annual Tax ÷ 12',
      explanation: 'Computes property tax burden assessed by local municipalities, counties, and school districts.',
      variables: [
        { symbol: 'Assessed Value', meaning: 'County tax assessor municipal valuation' },
        { symbol: 'Tax Rate', meaning: 'Effective millage percentage rate per $100 or $1,000' },
      ],
    },
    example: {
      title: 'Worked Example: $400,000 Assessed Home',
      scenario: 'A home assessed at $400,000 with a local effective property tax rate of 1.25%.',
      steps: [
        {
          number: 1,
          title: 'Calculate Annual Property Tax',
          description: '$400,000 × (1.25 ÷ 100) = $5,000/year.',
          mathExpression: '$5,000',
        },
        {
          number: 2,
          title: 'Calculate Monthly Escrow Reserve',
          description: '$5,000 ÷ 12 = $416.67/month.',
          mathExpression: '$416.67',
        },
      ],
      conclusion: 'The homeowner owes $5,000 annually or $416.67 per month in escrow reserves.',
    },
    faqs: [
      {
        question: 'How is assessed value different from market value?',
        answer: 'Market value is what buyers currently pay, whereas assessed value is the statutory figure assigned by municipal tax assessors to determine annual tax liability.',
      },
    ],
    inputs: [
      { id: 'assessed_value', label: 'Assessed Property Value', type: 'number', defaultValue: 400000, min: 1000, max: 50000000, unit: '$' },
      { id: 'tax_rate', label: 'Property Tax Rate', type: 'number', defaultValue: 1.25, min: 0.01, max: 20, step: 0.01, unit: '%' },
    ],
    defaultResult: {
      label: 'Annual Property Tax',
      initialValue: 5000,
      decimals: 2,
      secondaryText: 'Monthly Escrow: $416.67/month',
      prefix: '$',
      accent: 'violet',
    },
    computeScript: `
      const value = Math.max(0, Number(inputs.assessed_value) || 400000);
      const rate = Math.max(0, Number(inputs.tax_rate) || 1.25);
      const annual = value * (rate / 100);
      const monthly = annual / 12;
      return {
        value: annual,
        secondaryText: 'Monthly Escrow: $' + monthly.toFixed(2) + '/mo | Semi-Annual: $' + (annual / 2).toFixed(2),
        badge: rate > 2 ? 'High Millage' : 'Standard Rate'
      };
    `,
  },
];
