// scripts/sync-sitemap.mjs
import fs from 'node:fs';
import path from 'node:path';

const distClientDir = path.resolve('dist/client');
const publicDir = path.resolve('public');

const distSitemap0 = path.join(distClientDir, 'sitemap-0.xml');
const distSitemapIndex = path.join(distClientDir, 'sitemap-index.xml');
const distSitemapXml = path.join(distClientDir, 'sitemap.xml');
const publicSitemapXml = path.join(publicDir, 'sitemap.xml');

// 1. Recursive helper to discover all generated HTML routes
function getAllHtmlRoutes(dir, baseDir = dir) {
  let routes = [];
  if (!fs.existsSync(dir)) return routes;

  const entries = fs.readdirSync(dir, { withFileTypes: true });
  for (const entry of entries) {
    const fullPath = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      routes = routes.concat(getAllHtmlRoutes(fullPath, baseDir));
    } else if (entry.isFile() && entry.name.endsWith('.html')) {
      let relPath = path.relative(baseDir, fullPath).replace(/\\/g, '/');
      let routePath = '/';
      if (relPath === 'index.html') {
        routePath = '/';
      } else if (relPath.endsWith('/index.html')) {
        routePath = '/' + relPath.slice(0, -'index.html'.length);
      } else {
        routePath = '/' + relPath;
      }
      routes.push(routePath);
    }
  }
  return routes;
}

// 2. Discover all legitimate static HTML routes in dist/client
const validHtmlRoutes = new Set(getAllHtmlRoutes(distClientDir));

// Clean up any extra sitemap files from public
const publicExtras = ['sitemap-0.xml', 'sitemap-index.xml', 'sitemap.xsl'];
for (const extra of publicExtras) {
  const p = path.join(publicDir, extra);
  if (fs.existsSync(p)) fs.unlinkSync(p);
}

// Clean up any extra sitemap files from dist/client
const distExtras = [
  'sitemap.xsl',
  'sitemap-en-0.xml',
  'sitemap-es-0.xml',
  'sitemap-fr-0.xml',
  'sitemap-hi-0.xml',
];
for (const extra of distExtras) {
  const p = path.join(distClientDir, extra);
  if (fs.existsSync(p)) fs.unlinkSync(p);
}

// 3. Process sitemap generated by Astro
let rawXmlContent = '';
if (fs.existsSync(distSitemap0)) {
  rawXmlContent = fs.readFileSync(distSitemap0, 'utf-8');
} else if (fs.existsSync(distSitemapXml)) {
  rawXmlContent = fs.readFileSync(distSitemapXml, 'utf-8');
}

if (rawXmlContent) {
  // Extract individual <url>...</url> blocks
  const urlBlockRegex = /<url>([\s\S]*?)<\/url>/g;
  const filteredBlocks = [];
  const addedRoutes = new Set();
  let purgedLegacyCount = 0;
  let missingRoutePurged = 0;

  let match;
  while ((match = urlBlockRegex.exec(rawXmlContent)) !== null) {
    const blockContent = match[1];
    const locMatch = blockContent.match(/<loc>(https?:\/\/[^<]+)<\/loc>/);

    if (!locMatch) continue;

    const fullUrl = locMatch[1];
    const parsedUrl = new URL(fullUrl);
    const pathname = parsedUrl.pathname;

    // Filter out legacy /calculators/ and /calculator/ routes to eliminate 404s
    if (pathname.includes('/calculators/') || pathname.includes('/calculator/')) {
      purgedLegacyCount++;
      continue;
    }

    // Filter out non-public/internal patterns
    if (
      pathname.includes('/dev-preview') ||
      pathname.includes('/api/') ||
      pathname.includes('/admin/') ||
      pathname.includes('/draft/') ||
      /\/(404|500)(\/|$)/.test(pathname)
    ) {
      continue;
    }

    // Dynamic verification: Validate route exists in dist/client HTML output
    if (validHtmlRoutes.size > 0 && !validHtmlRoutes.has(pathname)) {
      missingRoutePurged++;
      continue;
    }

    // Reconstruct cleaned and formatted <url> block
    const cleanedBlock = blockContent
      .trim()
      .split('\n')
      .map((line) => '    ' + line.trim())
      .join('\n');

    filteredBlocks.push(`  <url>\n${cleanedBlock}\n  </url>`);
    addedRoutes.add(pathname);
  }

  // Ensure 100% of valid HTML routes on disk are included in sitemap.xml
  for (const route of validHtmlRoutes) {
    if (addedRoutes.has(route)) continue;
    if (
      route.includes('/dev-preview') ||
      route.includes('/api/') ||
      route.includes('/admin/') ||
      route.includes('/draft/') ||
      /\/(404|500)(\/|$)/.test(route)
    ) {
      continue;
    }

    const loc = `https://freeaccuratecalculator.com${route}`;
    const now = new Date().toISOString();
    let priority = '0.7';
    let changefreq = 'weekly';
    if (route === '/') {
      priority = '1.0';
      changefreq = 'daily';
    } else if (route.includes('-calculator') || route.includes('/sip/')) {
      priority = '0.7';
      changefreq = 'weekly';
    } else {
      priority = '0.5';
      changefreq = 'monthly';
    }

    filteredBlocks.push(`  <url>
    <loc>${loc}</loc>
    <lastmod>${now}</lastmod>
    <changefreq>${changefreq}</changefreq>
    <priority>${priority}</priority>
  </url>`);
    addedRoutes.add(route);
  }

  // Build clean, single sitemap.xml with xml namespaces
  const xmlHeader = '<?xml version="1.0" encoding="UTF-8"?>';
  const urlsetOpen = '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:news="http://www.google.com/schemas/sitemap-news/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml" xmlns:image="http://www.google.com/schemas/sitemap-image/1.1" xmlns:video="http://www.google.com/schemas/sitemap-video/1.1">';
  const urlsetClose = '</urlset>';

  const finalSitemapXml = `${xmlHeader}\n${urlsetOpen}\n${filteredBlocks.join('\n')}\n${urlsetClose}\n`;

  // Write single canonical sitemap.xml to both dist/client and public
  fs.writeFileSync(distSitemapXml, finalSitemapXml, 'utf-8');
  fs.writeFileSync(publicSitemapXml, finalSitemapXml, 'utf-8');

  // Clean up intermediate Astro chunked files
  if (fs.existsSync(distSitemap0)) fs.unlinkSync(distSitemap0);
  if (fs.existsSync(distSitemapIndex)) fs.unlinkSync(distSitemapIndex);

  console.log(`✅ Single sitemap.xml synchronized successfully.`);
  console.log(`   - Total Verified Live Routes: ${filteredBlocks.length}`);
  if (purgedLegacyCount > 0) {
    console.log(`   - Purged Legacy /calculators/* 404 Routes: ${purgedLegacyCount}`);
  }
  if (missingRoutePurged > 0) {
    console.log(`   - Purged Missing Non-Existent Routes: ${missingRoutePurged}`);
  }
  console.log(`   - All auxiliary chunk files cleaned up.`);
} else {
  console.warn('⚠️ No source sitemap file found in dist/client during build sync.');
}
